/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A plugin for the Web Application Specification Language
 */
export type Plugin1 = Plugin2 & Plugin3;
export type Plugin3 =
  | string
  | {
      name?: string;
      description?: string;
      version?: string;
      author?: string;
      main?: string;
      repository?: string;
      /**
       * The logic of the application to assemble.
       */
      graph: {
        /**
         * The composable units of the graph
         */
        nodes: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^([^_]+)(_[0-9])?$".
           */
          [k: string]: {
            src?: Plugin1;
            offload?: string | boolean;
            extensions?: {
              /**
               * This interface was referenced by `undefined`'s JSON-Schema definition
               * via the `patternProperty` "^.*$".
               */
              [k: string]: {
                /**
                 * This interface was referenced by `undefined`'s JSON-Schema definition
                 * via the `patternProperty` "^.*$".
                 */
                [k: string]: unknown;
              };
            };
          };
        };
        /**
         * The way that nodes are connected
         */
        edges: {
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };

/**
 * A plugin for the Web Application Specification Language
 */
export interface Plugin {
  name?: string;
  description?: string;
  version?: string;
  author?: string;
  main?: string;
  repository?: string;
  /**
   * The logic of the application to assemble.
   */
  graph: {
    /**
     * The composable units of the graph
     */
    nodes: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^([^_]+)(_[0-9])?$".
       */
      [k: string]: {
        src?: Plugin1;
        offload?: string | boolean;
        extensions?: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^.*$".
           */
          [k: string]: {
            /**
             * This interface was referenced by `undefined`'s JSON-Schema definition
             * via the `patternProperty` "^.*$".
             */
            [k: string]: unknown;
          };
        };
      };
    };
    /**
     * The way that nodes are connected
     */
    edges: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Plugin2 {
  name?: string;
  description?: string;
  version?: string;
  author?: string;
  main?: string;
  repository?: string;
  /**
   * The logic of the application to assemble.
   */
  graph: {
    /**
     * The composable units of the graph
     */
    nodes: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^([^_]+)(_[0-9])?$".
       */
      [k: string]: {
        src?: Plugin1;
        offload?: string | boolean;
        extensions?: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^.*$".
           */
          [k: string]: {
            /**
             * This interface was referenced by `undefined`'s JSON-Schema definition
             * via the `patternProperty` "^.*$".
             */
            [k: string]: unknown;
          };
        };
      };
    };
    /**
     * The way that nodes are connected
     */
    edges: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
